// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/sujin/Documents/herofactory/SSE_MVP/source/react-timeline-editor/node_modules/dumi/theme-default/builtins/Previewer/index.js';
